### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by psxjtwr01** [SkiffyMan/RLOrbital#1]
This is so cool tysm for taking the time to make this I will try and show this @MarlBurrow 😄

**Comment by SkiffyMan** [comment]
Thank you. I just updated Orbital to V1.0.3 that allows you to inject bakkes mod over multiple instances. This allows you to auto queue on every different instance. if you have any future feature suggestions please let me know.

**Comment by MarlBurroW** [comment]
Hi, I haven't had time to test RLOrbital yet, but it looks really nice. It's going to make launching much easier for people who aren't used to command lines, while waiting for an official UI. Thank you very much for your work man !

**Comment by SkiffyMan** [comment]
> @SkiffyMan Hi, I haven't had time to test RLOrbital yet, but it looks really nice. It's going to make launching much easier for people who aren't used to command lines, while waiting for an official UI. Thank you very much for your work man !

Thanks for the positive feedback!
