### ISSUE TITLE
MarlBot

### ISSUE THREAD

**Issue by JaxBruh** [SkiffyMan/RLOrbital#3]
So he removed the bot off of his GitHub Can you send it to me or post it giving credit to him?

**Comment by SkiffyMan** [comment]
Firstly, the use of RLMarlbot seems to be heavily used in ranked matches and has led to a 300% increase in cheat reports (I'm not sure about this source, but many things lead me to believe it's true). This increase might attract the attention of Epic, which could implement kernel-level anti-cheat measures. Such protection would ruin many great projects like bakkesmod, which would no longer be able to function. My goal is not to destroy the RL modding community. Closing the repository could thus artificially reduce the hype around Marlbot and smooth out the curve. 

This is one of the reasons I stopped supplying the MarlBot exe to help with this too. 

You can find it in other places if you look hard enough. I will not be supplying MarlBot.

**Comment by SamuelLachance** [comment]
ok but where did you get the source ? any chance i can find it anywhere ? i dont want the .exe i dont need it

**Comment by SamuelLachance** [comment]
i would like to add some bots , but i cant without the marlbot source

**Comment by SkiffyMan** [comment]
> i would like to add some bots , but i cant without the marlbot source

> ok but where did you get the source ? any chance i can find it anywhere ? i dont want the .exe i dont need it

The source is private and only a select few people have access to it. Soon there will be an update that allows bots to be added to Marl without the need of the source code. As said before, I will not be supplying MarlBot or the Source code.
