### ISSUE TITLE
Failed To Load Bot. Check if Bot.exe is in directory

### ISSUE THREAD

**Issue by Briickzy19288** [SkiffyMan/RLOrbital#5]
there is no bot exe directory, or no exe or anything that says Bot.exe, what do i do?
![image_2024-07-14_124509938](https://github.com/user-attachments/assets/a8b93bfd-c21a-4634-8bb7-5435eea26ad6)

**Comment by SkiffyMan** [comment]
You need a working version of Marlbot to use RLOrbital. It is not included. As I mentioned before to others who raised similar issues, I will not be supplying MarlBot. @Briickzy19288

**Comment by SkiffyMan** [comment]
.
