### ISSUE TITLE
doesn't work anymore

### ISSUE THREAD

**Issue by sourcive** [SkiffyMan/RLOrbital#7]
this doesn't function anymore and automatically bans you without even using the bot it errors saying "is bot.exe in the folder" and I don't know where to get bot.exe from

**Comment by SkiffyMan** [comment]
It works perfectly fine, you need to have Marlbot which I do not provide. As I mentioned before to others who raised similar issues, I will not be supplying MarlBot. @T-byte-sketch

**Comment by SkiffyMan** [comment]
.
