### ISSUE TITLE
Bot Doesn't Play Or Do Anything

### ISSUE THREAD

**Issue by Aaron-656** [SkiffyMan/RLOrbital#9]
Hello, whenever I run "RLOrbital.exe" with marlbot.exe renamed to "Bot.exe" and have started the bot with the correct rocket league proccess nothing happens in the game I have attatched some screenshots and for rocket league I am Using A Alternative Launcher Called "[Heroic](https://heroicgameslauncher.com/)" I have also used the built in launcher of "RLOrbital.exe" with the same path selected which I installed via Heroic (due to me not wanting to risk my main account or have a connection with my main account/game installation) and the terminal screenshot that i sent to you (that "RLOrbital.exe" opened) I did not Put Any Inputs into that terminal it automatically selected "Nexto" although ive selected NextMortal This Could be Something that I have done wrong but I am fairly sure i followed all the steps in the readme of this github repository and i downloaded "Marlbot" from this [link](https://www.unknowncheats.me/forum/other-games/633336-rlmarlbot.html) and the version of marlbot and the highest version that i can find so far is Version 1.3 hope I can get this fixed soon because this looks like a really good bot/launcher

![image](https://github.com/user-attachments/assets/f583d94d-3194-421c-bbc2-87c3b10f230c)
![image](https://github.com/user-attachments/assets/aedf97e3-ecc5-45ff-8eff-dfafbba924d9)
![image](https://github.com/user-attachments/assets/89248a10-2adc-45b5-be9e-971eb455cc61)

**Comment by SkiffyMan** [comment]
Hi friend, thanks for the detailed explanation, it's always appreciated for debugging. However, It is of no user error, It's simply the fact you're using an extremely outdated version of MarlBot which no longer works. You will need to find an upto date version (which there is). As I mentioned before to others who raised similar issues, I will not be supplying MarlBot, or where to find it.
